import 'dotenv/config'
import mongoose from 'mongoose'

import connectDB from '../src/config/db'
import Package from '../src/models/Package'

const DEFAULT_COUNT = 100
const DUMMY_USER_ID = process.env.SEED_CREATED_BY || '000000000000000000000001'

const adjectives = [
  'Hidden', 'Golden', 'Misty', 'Wild', 'Sacred', 'Emerald', 'Majestic', 'Moonlit', 'Ancient', 'Snowy',
]

const tripTypes = [
  'Mountain Escape', 'Beach Retreat', 'Forest Expedition', 'City Discovery', 'Desert Adventure',
  'Island Hopping', 'Cultural Trail', 'Wildlife Journey', 'Road Trip', 'River Camp',
]

const destinations = [
  'Ladakh', 'Sikkim', 'Manali', 'Goa', 'Andaman', 'Jaipur', 'Rishikesh', 'Meghalaya', 'Coorg', 'Kasol',
]

const seasonOptions = ['summer', 'winter', 'spring', 'autumn', 'all']

const spotsByDestination: Record<string, string[]> = {
  Ladakh: ['Pangong Lake', 'Nubra Valley', 'Magnetic Hill'],
  Sikkim: ['Tsomgo Lake', 'Nathula Pass', 'Yumthang Valley'],
  Manali: ['Solang Valley', 'Rohtang Pass', 'Old Manali'],
  Goa: ['Baga Beach', 'Dudhsagar Falls', 'Fontainhas'],
  Andaman: ['Radhanagar Beach', 'Neil Island', 'Cellular Jail'],
  Jaipur: ['Amber Fort', 'Hawa Mahal', 'City Palace'],
  Rishikesh: ['Laxman Jhula', 'Neer Waterfall', 'Ganga Aarti Ghat'],
  Meghalaya: ['Living Root Bridge', 'Umiam Lake', 'Dawki River'],
  Coorg: ['Abbey Falls', 'Raja Seat', 'Dubare Camp'],
  Kasol: ['Parvati River', 'Chalal Trail', 'Manikaran Sahib'],
}

const tagPool = [
  'Adventure', 'Nature', 'Luxury', 'Budget', 'Solo', 'Family', 'Weekend', 'Photography', 'Food', 'Trekking',
]

const permitPool = [
  'No special permit required',
  'Local ID required at check-in',
  'Carry government ID during travel',
  'Inner line permit needed for select spots',
]

const randomInt = (min: number, max: number): number => {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

const pickOne = <T>(items: T[]): T => items[randomInt(0, items.length - 1)]

const pickMany = <T>(items: T[], count: number): T[] => {
  const cloned = [...items]
  const picked: T[] = []

  while (cloned.length > 0 && picked.length < count) {
    const index = randomInt(0, cloned.length - 1)
    const [value] = cloned.splice(index, 1)
    if (value !== undefined) {
      picked.push(value)
    }
  }

  return picked
}

const formatDate = (date: Date): string => {
  return date.toISOString().slice(0, 10)
}

const buildPackage = (index: number) => {
  const adjective = pickOne(adjectives)
  const tripType = pickOne(tripTypes)
  const destination = pickOne(destinations)
  const duration = randomInt(3, 10)
  const startOffset = randomInt(3, 120)
  const startDate = new Date()
  startDate.setDate(startDate.getDate() + startOffset)

  const endDate = new Date(startDate)
  endDate.setDate(endDate.getDate() + duration - 1)

  const budget = randomInt(12000, 95000)
  const destinationSpots = spotsByDestination[destination] ?? ['Local Market', 'Sunset Point', 'Main Square']
  const spotCount = Math.min(destinationSpots.length, randomInt(2, 3))

  return {
    name: `${adjective} ${destination} ${tripType} #${index + 1}`,
    description: `Enjoy a ${duration}-day curated trip to ${destination} with guided experiences, local stays, and memorable activities.`,
    coverImage: `https://picsum.photos/seed/alpine-trip-${index + 1}/1280/720`,
    season: pickOne(seasonOptions),
    budget,
    destination,
    spots: pickMany(destinationSpots, spotCount),
    duration,
    startDate: formatDate(startDate),
    endDate: formatDate(endDate),
    identification: Math.random() > 0.35,
    permit: pickOne(permitPool),
    tags: pickMany(tagPool, randomInt(2, 4)),
    affiliateLinks: [`https://example.com/deals/${destination.toLowerCase()}-${index + 1}`],
    additional: 'Generated by seedRandomPackages script',
    createdBy: DUMMY_USER_ID,
    hotels: [],
    vehicles: [],
    approved: true,
  }
}

const run = async (): Promise<void> => {
  const countArg = Number(process.argv[2])
  const count = Number.isInteger(countArg) && countArg > 0 ? countArg : DEFAULT_COUNT

  try {
    await connectDB()

    const docs = Array.from({ length: count }, (_, index) => buildPackage(index))
    const inserted = await Package.insertMany(docs)

    console.log(`Inserted ${inserted.length} random packages successfully.`)
  } catch (error) {
    console.error(
      `Failed to seed random packages: ${error instanceof Error ? error.message : 'Unknown error'}`,
    )
    process.exitCode = 1
  } finally {
    await mongoose.disconnect()
  }
}

void run()
